module.exports.descriptors = [
    'Concrete',
    'Carpark',
    'Park',
    'Area',
    'Radington',
    'Grindville',
    'Fliptrick',
    'Manual',
    'Kickflip',
    'Victoria',
    'Mile End',
    'Walthamstow',
    'South Bank',
    'Bowie',
    'Mongo',
    'Switch',
    'Arial',
    'Drop-in'

]
module.exports.places = [
    'Park',
    'Flats',
    'Village',
    'Camp',
    'Town',
    'Backcountry',
    'Bowl',
    'Halfpipe',
    'Sands',
    'Cliffs',
    'Hollow',
    'River',
    'Pipe',
    'Sketch',
    'Gym',
    'Euphoria',
    'Skate park',
    'Indoor spot',
    'Transfer',
    'Schoolyard',
    'Pipedream'
]